### ISSUE TITLE
NoMethodError on regular invocation

### ISSUE THREAD

**Issue by debugloop** [jreinert/passed#2]
Hello, I just tried to use this to adapt my pass files to the change from `UserName` to `user`. I run the latest Arch Linux with passed installed from AUR and have issued the command from your `README.md`, `passed 's/UserName/user/'`, but get this following error after confirming the first entry with `y`:

``` ruby
/usr/bin/passed:36:in `block in <main>': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
    from /usr/bin/passed:17:in `block in each_entry_with_key'
    from /usr/bin/passed:17:in `each'
    from /usr/bin/passed:17:in `each_entry_with_key'
    from /usr/bin/passed:20:in `<main>'
```

Thanks!

**Comment by repomaa** [comment]
Sorry i took so long. Was off my radar somehow.
